export const horizontalPadding = '1em'
export const basePadding = '1em'
export const contentPadding = '1rem 2rem'
export const baseMobileXPadding = '1rem'
export const baseMobileYPadding = '2rem'
export const baseMobilePadding = '2rem 1rem'
export const mobileCategoryHeroPadding = '2rem 1rem'
export const verticalPadding = '1em'
export const baseMargin = '1em'
export const pageWidth = '1279px'
export const articleWidth = '680px'
export const articleMargin = '102px'
export const articleContainerWidth = '1088px'
export const gutter = '14px'
export const gridGap = '6rem'
export const mobileScreenSize = 1279
export const mediumScreenSize = 885
export const miniScreenSize = 350
export const tabletWidth = "768px"
